[project]
name = "libdatachannel-py"
version = "2025.1.0.dev0"
description = "libdatachannel-py is a Python binding for libdatachannel."
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.13"

[project.urls]
Source = "https://github.com/shiguredo/libdatachannel-py"
Discord = "https://discord.gg/shiguredo"

[build-system]
requires = ["setuptools==80.2", "wheel==0.45.1"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "nanobind>=2.7.0",
    "pytest>=8.3.5",
    "setuptools>=80.2",
    "build>=1.2.2.post1",
    "wheel>=0.45.1",
]

[tool.ruff]
target-version = "py313"
line-length = 100
