[project]
name = "libdatachannel-py"
version = "0.1.0"
description = "libdatachannel-py is a Python binding for libdatachannel."
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["setuptools==80.2", "wheel==0.45.1"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "nanobind>=2.7.0",
    "pytest>=8.3.5",
    "setuptools>=80.2.0",
]

[tool.ruff]
target-version = "py311"
line-length = 100
